// examples/solid/src/components/text-input.tsx
import type { FormSolid } from "@lucas-barake/effect-form-solid"
import * as Option from "effect/Option"
import { Show } from "solid-js"
import styles from "../styles/form.module.css"

export const TextInput: FormSolid.FieldComponent<string> = (props) => (
  <div class={styles.fieldContainer}>
    <input
      type="text"
      value={props.field.value}
      onInput={(e) => props.field.onChange(e.currentTarget.value)}
      onBlur={props.field.onBlur}
      class={`${styles.input} ${Option.isSome(props.field.error) ? styles.error : ""}`}
    />
    <Show when={props.field.isValidating}>
      <span class={styles.validatingText}>
        Validating...
      </span>
    </Show>
    <Show when={Option.isSome(props.field.error)}>
      <span class={styles.errorText}>
        {Option.getOrElse(props.field.error, () => "")}
      </span>
    </Show>
  </div>
)

// examples/src/components/text-input.tsx
import type { FormReact } from "@lucas-barake/effect-form-react"
import * as Option from "effect/Option"
import styles from "../styles/form.module.css"

export const TextInput: FormReact.FieldComponent<string> = ({ field }) => (
  <div className={styles.fieldContainer}>
    <input
      type="text"
      value={field.value}
      onChange={(e) =>
        field.onChange(e.target.value)}
      onBlur={field.onBlur}
      className={`${styles.input} ${Option.isSome(field.error) ? styles.error : ""}`}
    />
    {field.isValidating && (
      <span className={styles.validatingText}>
        Validating...
      </span>
    )}
    {Option.isSome(field.error) && (
      <span className={styles.errorText}>
        {field.error.value}
      </span>
    )}
  </div>
)
